export const ROUTE_DASHBOARD = "Dashboard"
export const ROUTE_DECK_CREATE = "DeckCreate"
export const ROUTE_DECK_OVERVIEW = "DeckOverview"
export const ROUTE_DECK_QUIZ = "DeckQuiz"
export const ROUTE_DECK_DASHBOARD = "DeckDashboard"
export const ROUTE_DECK_CARD_CREATE = "DeckCardCreate"
export const ROUTE_DECK_CARD_EDIT = "DeckCardEdit"
